### ISSUE TITLE
Failed tests

### ISSUE THREAD

**Issue by Stefan-Dienst** [HugoStrand/tprf#4] opened 2019-01-31 16:44 UTC
After installation I ran `make test`, showing that multiple tests failed.

> 47% tests passed, 9 tests failed out of 17
> 
> Total Test time (real) =   2.13 sec
> 
> The following tests FAILED:
> 	  9 - g_wk_to_from_g_wr (Failed)
> 	 10 - chi00_square_lattice (Failed)
> 	 11 - bse_and_rpa_loc_vs_latt (Failed)
> 	 12 - mean_field (Failed)
> 	 13 - mean_field_kanamori (Failed)
> 	 14 - hartree_response (Failed)
> 	 15 - 1d_hubbard_hf_rpa (Failed)
> 	 16 - 1d_hubbard_hf_spin_rot_inv (Failed)
> 	 17 - 1d_hubbard_hf_rpa_2site_AFM (Failed)
> Errors while running CTest
> Makefile:94: recipe for target 'test' failed
> make: *** [test] Error 8
> 

Did I do something wrong in the installation?

**Comment by HugoStrand** [comment] 2019-01-31 18:52
Liebe Stefan,

Thank you for reporting the issues! The build, test and install structure of tprf has not been used by many people other than me. So I am sorry for the problems that you are encountering.

Could you please try two things. 

1. Run one of the failing tests manually to get more output from the test, in particular the error message, e.g.
```
ctest mean_field
```
This should give you a better idea of what is going wrong.

2. I think the errors are caused by the tests not finding the `triqs_tprf` python module. This is a problem that should be fixed. But a workaround is to first run `make install` and then add the proper install path to your `PYTHONPATH`. To check that your environment is correctly set up running
```
python -c "import triqs_tprf"
```
should execute without any error. Once this is working please try to run the tests again.

MFG / Hugo

**Comment by Stefan-Dienst** [comment] 2019-02-01 15:41
Dear Hugo,

thanks for the quick response!

I checked what error the tests threw and the problem was, that i was missing your `pyed` package.
I added it to the `PYTHONPATH` and I checked that the environment is properly set up and I can import everything.
Now only one test fails.
```
94% tests passed, 1 tests failed out of 17

Total Test time (real) =   5.25 sec

The following tests FAILED:
	 17 - 1d_hubbard_hf_rpa_2site_AFM (Failed)
Errors while running CTest
Makefile:94: recipe for target 'test' failed
make: *** [test] Error 8
```
If I run this test script individually I get following error message.
```
Traceback (most recent call last):
  File "1d_hubbard_hf_rpa_2site_AFM.py", line 203, in <module>
    "Error: The AF susceptibility and order parameter do not agree."
AssertionError: Error: The AF susceptibility and order parameter do not agree.
```
So this line
```
    assert( np.array_equal(np.abs(m_AF) < 1e-9, chi_AF.real > 0.) ), \
        "Error: The AF susceptibility and order parameter do not agree."
```
throws the error.

Taking a closer look at the object that are compared reveals that the last 4 elements of `m_AF` could be regarded as numerical zero but are bigger than `1e-9`.
```
np.abs(m_AF)=[6.250e-01 6.151e-01 6.027e-01 5.871e-01 5.667e-01 5.392e-01 5.001e-01 4.408e-01 3.385e-01 4.793e-08 4.247e-08 4.139e-09 4.745e-10]
chi_AF.real=[-0.223 -0.251 -0.287 -0.335 -0.402 -0.504 -0.673 -1.014 -2.058 70.481  1.945  0.986  0.66 ]
```
So setting the cut-off to `1e-7` let's me pass the test, but what could be the reason for these numerical accuracy differences?

Cheers
Stefan

**Comment by HugoStrand** [comment] 2019-02-04 14:14
Dear Stefan,

Thank you for reporting. I have tuned down the tolerance in this test to `1e-6`  in the commit 41d32d4a289fcaa7fc58106932cc6e3e0ecc4817. I was probably a bit too optimistic about the accuracy of the calculation.

Cheers, Hugo

**Closed as completed by HugoStrand** 2019-02-04 14:14 UTC
